<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net462</TargetFramework><AssemblyName>CrystalProjectRandomMusic</AssemblyName><EnableDefaultCompileItems>false</EnableDefaultCompileItems><GenerateAssemblyInfo>false</GenerateAssemblyInfo><Deterministic>true</Deterministic></PropertyGroup>
  <ItemGroup><Compile Include="Music.cs"/><PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all"/></ItemGroup>
</Project>
